### ISSUE TITLE
Permissions Workflow for Groups Example

### ISSUE THREAD

**Issue by jdkang** [microsoftgraph/graphql-demo#5]
I realize this might be a permissions issue, but not sure if I need to `consent` the AADv2 auth tokens in a specific way to get the example to work with the `groups` endpoint.

# Issue
Attempting to execute the example group query which hits 
```
{
  groups {
    displayName
    description
    members {
      id
    }
  }
}
```
Result:
```
{
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field Query.groups.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "groups"
      ]
    }
  ],
  "data": {
    "groups": null
  }
}
```
From the console:
```
GraphQL API server running on port:1337
{ StatusCodeError: 403 - "{\r\n  \"error\": {\r\n    \"code\": \"Authorization_RequestDenied\",\r\n
  \"message\": \"Insufficient privileges to complete the operation.\",\r\n    \"innerError\": {\r\n
    \"request-id\": \"2506310d-deda-4284-8004-db376b2818d7\",\r\n      \"date\": \"2018-02-15T18:32:18\"\r\n    }\r\n  }\r\n}"
    at new StatusCodeError (C:\github\graphql-demo\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\github\graphql-demo\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\github\graphql-demo\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\github\graphql-demo\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\github\graphql-demo\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\github\graphql-demo\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 403,
  message: '403 - "{\\r\\n  \\"error\\": {\\r\\n    \\"code\\": \\"Authorization_RequestDenied\\",\\r\\n    \\"message\\": \\"Insufficient privileges to complete the operation.\\",\\r\\n    \\"innerError\\": {\\r\\n      \\"request-id\\": \\"2506310d-deda-4284-8004-db376b2818d7\\",\\r\\n      \\"date\\": \\"2018-02-15T18:32:18\\"\\r\\n    }\\r\\n  }\\r\\n}"',
  error: '{\r\n  "error": {\r\n    "code": "Authorization_RequestDenied",\r\n    "message": "Insufficient privileges to complete the operation.",\r\n    "innerError": {\r\n      "request-id": "2506310d-deda-4284-8004-db376b2818d7",\r\n      "date": "2018-02-15T18:32:18"\r\n    }\r\n  }\r\n}',
  options:
   { url: 'https://graph.microsoft.com/v1.0/groups',
```

# Steps Taken
1. Generated an AD v2 ("convergent") API Key through dev portal
    * Web platform
    * Redirect URI: `http://localhost:1337`
    * Delegated Permissions: same as those listed in `applicationConfig.scopes` object in `index.html`
2. Update `index.html`
3. `[...] npm start`
4. SSO with personal creds

**Comment by dpim** [comment]
I think you'll need to update the permissions requested in `index.html` to include `Group.Read.All` as this GraphQL query will call the [list groups API](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_list).
